import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ga4/manual",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          minHeight: "95dvh",
          display: "flex",
          flexDirection: "column",
        }}
      >
        {children}
        <footer
          style={{
            marginTop: "auto",
          }}
        >
          <Link href="/">Back to Home</Link>
        </footer>
      </body>
    </html>
  );
}
